### ISSUE TITLE
配置好后，引用报错

### ISSUE THREAD

**Issue by Dorisfeng** [dongyuanxin/webpack-demos#4]
![image](https://user-images.githubusercontent.com/31895359/53682735-81b10800-3d33-11e9-9f2a-c8462c08fabf.png)
使用create-react-app 创建的项目，客户那不连外网，项目需要的第三方依赖要下载到本地。我按照教程配置好后，在app.js中引用报错
![image](https://user-images.githubusercontent.com/31895359/53682772-27647700-3d34-11e9-834e-06dbcf2bbbcf.png)
谢谢

**Comment by dongyuanxin** [comment]
具体项目的配置不属于仓库内容
